### ISSUE TITLE
About target preparation

### ISSUE THREAD

**Issue by ZhongYingMatrix** [xieenze/PolarMask#12]
Hi, sorry to bother you again. 
I notice that u fix the size of imgs at (1280, 768), and I get lots of bug when I  try to keep img ratio.
I wonder whether it is target preparation in coco_seg.py that cause those problems. Have u try to keep img ratio instead of fixed size?

**Comment by xieenze** [comment]
Hi,
Yes, I have a config example of keep image ratio in [this config](https://github.com/xieenze/PolarMask/blob/master/configs/polarmask/32gpu/polar_800_1x_r50.py).
If you keep ratio, you need to set '**size_divisor=128**'.
I found that the results are the same in these two methods. 
Thanks.

**Comment by ZhongYingMatrix** [comment]
@xieenze I finally find that imgs_per_gpu needs to be set at 1 if we need to keep ratio, otherwise loss in polarmask_head will not work for different shape of _gt_bboxes&labels&masks.
So it's hard to train on less gpu(ex. 4 gpus take 3-4 days for 1x scheduler, and batchsize on 4 leads to unstability) when keeping ratio, unless rewriting loss in head or dataset.
Thanks a lot~

**Comment by xieenze** [comment]
@ZhongYingMatrix 
Yes, it is a potential problem. Because I write the label generation outside the network. 

But I think if you use single scale and keep the ratio(e.g. the short side=800 and the longer side<=1333), the batch size can be set >1. Like the config I provide to you.

I only find that if I use mstrain, the batch need to set to 1.   

Because the label generation is relative complex, put it inside the network may make it slow.  So I generate label in coco_seg.py.

**Comment by andgitchang** [comment]
@xieenze 
I found that using smaller scale (said, shorter side = 384) may potentially induce 'divide by zero' and 'invalid value' warning at [these lines](https://github.com/xieenze/PolarMask/blob/90c479856fa8aa1e2d519886df5a5f8a58a4aaf2/mmdet/datasets/coco_seg.py#L512). Does [try catch fraction](https://github.com/xieenze/PolarMask/blob/90c479856fa8aa1e2d519886df5a5f8a58a4aaf2/mmdet/datasets/coco_seg.py#L522) correctly handle RuntimeWarning either? Or what else can we do, consider regime of training low resolution images ? Thanks.
