### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by LetsGoFir** [xieenze/PolarMask#18]
`mask centerness is smaller than origin centerness, so add a constant is important or the score will be 
too low.`
It is in your 'mmdet/models/anchor_heads/polarmask_head.py', if the centerness is din/dmax, then it should not be negtive, but actually it has.

**Comment by LetsGoFir** [comment]
I see, the centerness is a regression problem, and you use it to weight the classification score, so in fact there is no center prediction in your paper. Your center sample in Mask Assembling is every pixel in the (multi level) feature map.
Thanks.
But I still do not know why the centerness prediction have negative value.

**Comment by xieenze** [comment]
Hi,
Thanks for you question.
During training, the gt centerness is positive and we use it as weight for loss calc.  And the pred centeress is out by an only conv so it may be nagative.  But it does not matters.
During inference, The centercess prediction cannot be negative because we use sigmoid on centerness prediction.
