### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by HouHou0925** [xieenze/PolarMask#26]
不好意思又打擾您了
問題1:
在使用coco_seg_fast時
所訓練出來的mask方向會是錯的
coco_seg則沒問題

問題2:
在計算MaskIOULoss時
會出現NaN的情況
不知道是什麼樣的情況會造成

**Comment by xieenze** [comment]
hi
first, the coco_seg_fast is outdate, I forget to delete it. I forget why the orientation is wrong.... But it didn't faster than coco_seg.py. So you can ignore it.
second, I didn't meet the case for 'maskiouloss nan'. You can check whether you give the correct mask GT.  Because in the correct mask GT the min distance is 1e-6. and the maskiou='36 distance min/max'. So it can not meet NAN problem.

**Comment by HouHou0925** [comment]
非常感謝您快速的回覆~!!

目前找不到我的數據問題是發生在哪裡
我將生成的36個距離印出來後發現
tensor([0.0000e+00, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06,
        1.0000e-06, 1.0000e-06, 1.0000e-06, 1.8000e+01, 2.0396e+01, 2.1541e+01,
        2.3324e+01, 2.6249e+01, 2.7019e+01, 2.4187e+01, 2.2136e+01, 2.0224e+01,
        2.0000e+01, 2.0396e+01, 1.0770e+01, 8.0623e+00, 6.4031e+00, 5.0000e+00,
        1.0000e-06, 3.1623e+00, 1.0000e-06, 3.0000e+00, 1.0000e-06, 3.1623e+00,
        1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06, 1.0000e-06])

有些的[0]位置會是0  (只有[0]位置有出現過0)
但不知道是為什麼

所以暫時先在 coco_seg  line:592
加上
if i in new_coordinate.keys() and d <= 0  :
                new_coordinate[i] = 1e-6
