### ISSUE TITLE
Questions about Distance Label Generation Algorithm

### ISSUE THREAD

**Issue by josiehong** [xieenze/PolarMask#38]
Hi, thanks for sharing the code. 

When I was training PolarMask, I noticed there are a lot of coordinate be targeted as the minimum number 10^-6. I am confused about why not chose the points outside $\Delta \theta$. Does this affect the results?

Thanks a lot!

**Comment by xieenze** [comment]
Hi
Great question. 
(1) some positive samples which are outside the mask, the distance in certain angles are set to a small value e.g. 10-6. Because these outliers have no Intersection with GT contours.
(2) These positive samples will not affect the final result, because these are **low-quality** positive samples(please refer to the definition of 'CenterNess'). So during inference the score of these outliers is low, and will be removed by NMS.
